app/services/__init__.py
from flask import Blueprint

sort_bp = Blueprint("sort_bp", __name__, template_folder="templates")


from . import views

app/services/views.py
from flask import render_template, request, flash
from sqlalchemy.orm import joinedload
from sqlalchemy import asc, desc
from . import sort_bp
from database import get_db
from database.models import Category, GeneralService, LabService, Lab, UnmatchedService

@sort_bp.route('/general_services', methods=['GET'])
def general_services():
    db = next(get_db())

    categories = db.query(Category).all()
    selected_category_id = request.args.get('category', type=int)
    min_price = request.args.get('min_price', type=int)
    max_price = request.args.get('max_price', type=int)
    search = request.args.get('search', type=str)
    sort_by = request.args.get('sort_by', default='name', type=str)
    sort_order = request.args.get('sort_order', default='asc', type=str)

    order = asc if sort_order == 'asc' else desc

    # еталонні послуги
    query = db.query(GeneralService).options(joinedload(GeneralService.lab_services).joinedload(LabService.lab))

    if selected_category_id:
        query = query.filter(GeneralService.category_ids.any(selected_category_id))

    if search:
        query = query.filter(GeneralService.name.ilike(f'%{search}%'))

    services = query.all()
    has_general_services = bool(services)

    if has_general_services:
        filtered_services = []
        checked_lab_services = []
        for service in services:
            unique_lab_services = []
            for lab_service in service.lab_services:
                if (min_price is None or lab_service.price >= min_price) and (
                        max_price is None or lab_service.price <= max_price):
                    is_duplicate = any(
                        existing_service['name'] == lab_service.original_name and
                        existing_service['lab_name'] == lab_service.lab.lab_name
                        for existing_service in checked_lab_services
                    )
                    if not is_duplicate:
                        unique_lab_services.append(lab_service)
                        checked_lab_services.append(
                            {'name': lab_service.original_name, 'lab_name': lab_service.lab.lab_name})

            if unique_lab_services:
                service.lab_services = unique_lab_services
                # перевірка, щоб не додавати еталонну послугу, яка має лише одну лабораторну послугу
                if len(service.lab_services) > 1:
                    filtered_services.append(service)


        if sort_by == 'price':
            filtered_services.sort(
                key=lambda s: min((ls.price for ls in s.lab_services), default=float('inf')),
                reverse=(sort_order == 'desc')
            )
        elif sort_by == 'name':
            filtered_services.sort(
                key=lambda s: min((ls.original_name for ls in s.lab_services), default=""),
                reverse=(sort_order == 'desc')
            )

        return render_template(
            'general_services.html',
            services=filtered_services,
            categories=categories,
            selected_category_id=selected_category_id,
            min_price=min_price,
            max_price=max_price,
            sort_by=sort_by,
            sort_order=sort_order,
            search=search,
            has_general_services=True
        )

    else:
        # послуги лабораторій без еталонних
        unmatched_services = db.query(UnmatchedService).filter(
            UnmatchedService.category_id == selected_category_id).all()
        lab_service_ids = [unmatched_service.lab_service_id for unmatched_service in unmatched_services]
        lab_services_query = db.query(LabService).filter(LabService.id.in_(lab_service_ids))


        if search:
            lab_services_query = lab_services_query.filter(LabService.original_name.ilike(f'%{search}%'))


        if min_price is not None:
            lab_services_query = lab_services_query.filter(LabService.price >= min_price)
        if max_price is not None:
            lab_services_query = lab_services_query.filter(LabService.price <= max_price)

        lab_services = lab_services_query.all()


        if sort_by == 'name':
            lab_services.sort(
                key=lambda ls: ls.original_name.lower() if ls.original_name else '',
                reverse=(sort_order == 'desc')
            )
        elif sort_by == 'price':
            lab_services.sort(
                key=lambda ls: ls.price if ls.price is not None else float('inf'),
                reverse=(sort_order == 'desc')
            )

        return render_template(
            'general_services.html',
            services=lab_services,
            categories=categories,
            selected_category_id=selected_category_id,
            min_price=min_price,
            max_price=max_price,
            sort_by=sort_by,
            sort_order=sort_order,
            search=search,
            has_general_services=False
        )



@sort_bp.route('/all_services', methods=['GET'])
def all_services():
    db = next(get_db())

    min_price = request.args.get('min_price', type=int)
    max_price = request.args.get('max_price', type=int)
    search = request.args.get('search', type=str)
    sort_by = request.args.get('sort_by', default='name', type=str)
    sort_order = request.args.get('sort_order', default='asc', type=str)
    selected_lab = request.args.get('selected_lab', type=int)

    order = asc if sort_order == 'asc' else desc


    labs = db.query(Lab).all()


    query = db.query(LabService).join(Lab).options(joinedload(LabService.lab))

    if search:
        query = query.filter(LabService.original_name.ilike(f'%{search}%'))

    if min_price is not None:
        query = query.filter(LabService.price >= min_price)
    if max_price is not None:
        query = query.filter(LabService.price <= max_price)


    if selected_lab:
        query = query.filter(LabService.lab_id == selected_lab)

    lab_services = query.all()

    lab_services = [service for service in lab_services if service.price and service.price > 10]


    if sort_by == 'price':
        lab_services.sort(key=lambda ls: ls.price if ls.price is not None else float('inf'),
                          reverse=(sort_order == 'desc'))
    elif sort_by == 'name':
        lab_services.sort(
            key=lambda ls: ls.original_name.lower() if ls.original_name else '',
            reverse=(sort_order == 'desc')
        )
    elif sort_by == 'lab_name':
        lab_services.sort(
            key=lambda ls: ls.lab.name.lower() if ls.lab and ls.lab.name else '',
            reverse=(sort_order == 'desc')
        )

    return render_template(
        'all_services.html',
        services=lab_services,
        labs=labs,
        min_price=min_price,
        max_price=max_price,
        sort_by=sort_by,
        sort_order=sort_order,
        search=search,
        selected_lab=selected_lab
    )

app/services/templates/all_services.html
{% extends 'base.html' %}

{% block title %}
  Всі лабораторні послуги
{% endblock %}

<head>
    <script src="{{ url_for('static', filename='js/script2.js') }}"></script>
</head>

{% block body_class %}bg-custom-map{% endblock %}

{% set no_break_top = True %}
{% if not no_break_top %}
    <div class="break-top"></div>
{% endif %}

{% block content %}

<div class="container-fluid retreat">

    <div class="row">
        <div class="col-md-4 text-light mb-5">
            <div class="container">
            <h3 class="text-light mt-4 mb-4">Сортування</h3>
            <form method="GET" action="{{ url_for('sort_bp.all_services') }}">
                <div class="mb-3">
                    <label for="search" class="form-label">Пошук за назвою</label>
                    <input type="text" id="search" name="search" class="form-control" value="{{ search or '' }}">
                </div>


                <div class="mb-3">
                    <label for="min_price" class="form-label">Мінімальна ціна</label>
                    <input type="number" id="min_price" name="min_price" class="form-control" value="{{ min_price or '' }}" min="0">
                </div>
                <div class="mb-3">
                    <label for="max_price" class="form-label">Максимальна ціна</label>
                    <input type="number" id="max_price" name="max_price" class="form-control" value="{{ max_price or '' }}" min="0">
                </div>

                <div class="mb-3">
                    <label for="selected_lab" class="form-label">Лабораторія</label>
                    <select id="selected_lab" name="selected_lab" class="form-select">
                        <option value="">Виберіть лабораторію</option>
                        {% for lab in labs %}
                            <option value="{{ lab.id }}" {% if lab.id == selected_lab %}selected{% endif %}>{{ lab.lab_name }}</option>
                        {% endfor %}
                    </select>
                </div>


                <div class="mb-3">
                    <label for="sort_by" class="form-label">Сортувати за</label>
                    <select id="sort_by" name="sort_by" class="form-select">
                        <option value="name" {% if sort_by == 'name' %}selected{% endif %}>Назвою</option>
                        <option value="price" {% if sort_by == 'price' %}selected{% endif %}>Ціною</option>
                    </select>
                </div>


                <div class="mb-3">
                    <label for="sort_order" class="form-label">Порядок сортування</label>
                    <select id="sort_order" name="sort_order" class="form-select">
                        <option value="asc" {% if sort_order == 'asc' %}selected{% endif %}>За зростанням</option>
                        <option value="desc" {% if sort_order == 'desc' %}selected{% endif %}>За спадаючим</option>
                    </select>
                </div>

                <button type="submit" class="btn btn-secondary button-hover">Відсортувати</button>
            </form>
            </div>
        </div>

        <!-- блок для виведення лабораторних послуг -->
        <div class="col-md-8 bg-custom mb-5">
            <div class="container">
            <h2 class="mb-4 mt-4">Лабораторні послуги</h2>
            <div class="list-group">
                {% for lab_service in services %}
                    <div class="list-group-item mb-3 mt-2 lab-service-item">
                        <h4 class="mb-1 service-title" data-service-id="{{ lab_service.id }}">
                            {{ lab_service.original_name }}
                        </h4>

                        <div class="lab-service-info">
                            <p><strong>Ціна:</strong> {{ lab_service.price }} грн</p>
                            <p><strong>Час виконання:</strong> {{ lab_service.execution_time }}</p>
                            <p><strong>Лабораторія:</strong> {{ lab_service.lab.lab_name }}</p>
                        </div>
                        <a href="{{ lab_service.url }}" class="btn btn-sm btn-primary button-hover" target="_blank">Перейти</a>
                    </div>
                {% endfor %}
            </div>
        </div>
        </div>
    </div>
</div>


{% block footer %}

{% include "footer.html" %}
{% endblock %}
{% endblock %}

app/services/templates/general_services.html
{% extends 'base.html' %}

{% block title %}
  Список послуг
{% endblock %}

<head>
    <script src="{{ url_for('static', filename='js/script2.js') }}"></script>
</head>

{% block body_class %}bg-custom-map{% endblock %}

{% set no_break_top = True %}
{% if not no_break_top %}
    <div class="break-top"></div>
{% endif %}

{% block content %}

<div class="container-fluid retreat">

    <div class="row">

        <div class="col-md-4 text-light mb-5">
            <div class="container">
            <h3 class="text-light mt-4 mb-4">Сортування</h3>
            <form method="GET" action="{{ url_for('sort_bp.general_services') }}">

                <div class="mb-3">
                    <label for="search" class="form-label">Пошук за назвою</label>
                    <input type="text" id="search" name="search" class="form-control" value="{{ search or '' }}">
                </div>
                <div class="mb-3">
                    <label for="category" class="form-label">Категорія</label>
                    <select id="category" name="category" class="form-select">
                        <option value="">Виберіть категорію</option>
                        {% for category in categories %}
                            <option value="{{ category.id }}" {% if category.id == selected_category_id %}selected{% endif %}>{{ category.name }}</option>
                        {% endfor %}
                    </select>
                </div>


                <div class="mb-3">
                    <label for="min_price" class="form-label">Мінімальна ціна</label>
                    <input type="number" id="min_price" name="min_price" class="form-control" value="{{ min_price or '' }}" min="0">
                </div>
                <div class="mb-3">
                    <label for="max_price" class="form-label">Максимальна ціна</label>
                    <input type="number" id="max_price" name="max_price" class="form-control" value="{{ max_price or '' }}" min="0">
                </div>


                <div class="mb-3">
                    <label for="sort_by" class="form-label">Сортувати за</label>
                    <select id="sort_by" name="sort_by" class="form-select">
                        <option value="name" {% if sort_by == 'name' %}selected{% endif %}>Назвою</option>
                        <option value="price" {% if sort_by == 'price' %}selected{% endif %}>Ціною</option>
                    </select>
                </div>


                <div class="mb-3">
                    <label for="sort_order" class="form-label">Порядок сортування</label>
                    <select id="sort_order" name="sort_order" class="form-select">
                        <option value="asc" {% if sort_order == 'asc' %}selected{% endif %}>За зростанням</option>
                        <option value="desc" {% if sort_order == 'desc' %}selected{% endif %}>За спадаючим</option>
                    </select>
                </div>

                <button type="submit" class="btn btn-secondary button-hover">Відсортувати</button>
            </form>
            </div>
        </div>

        <!-- блок для виведення еталонних послуг -->
        {% if has_general_services %}
        <div class="col-md-8 bg-custom mb-5">
            <div class="container">
            <h2 class="mb-4 mt-4">Еталонні послуги</h2>
            <div class="list-group">
                {% for service in services %}
                    <div class="list-group-item mb-3 mt-2 lab-service-item">
                        <h4 class="mb-1 service-title" data-service-id="{{ service.id }}">
                            {{ service.name }}
                        </h4>

                        <!-- лабораторні послуги для еталонної послуги -->
                        <div class="lab-services-list mt-2 {% if min_price or max_price %}d-block{% else %}d-none{% endif %}" id="service-{{ service.id }}">
                            {% for lab_service in service.lab_services %}
                                <div class="lab-service-item1 mb-3 p-3 d-flex justify-content-between align-items-center">
                                    <div class="lab-service-info">
                                        <h5><strong>{{ lab_service.original_name }}</strong></h5><br>
                                        <p><strong>Ціна:</strong> {{ lab_service.price }} грн</p>
                                        <p><strong>Час виконання:</strong> {{ lab_service.execution_time }}</p>
                                        <p><strong>Лабораторія:</strong> {{ lab_service.lab.lab_name }}</p>
                                    </div>
                                    <a href="{{ lab_service.url }}" class="btn btn-sm btn-primary button-hover" target="_blank">Перейти</a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        </div>
        {% else %}
        <!-- блок для виведення лабораторних послуг -->
        <div class="col-md-8 bg-custom mb-5">
            <div class="container">
            <h2 class="mb-4 mt-4">Лабораторні послуги</h2>
            <div class="list-group">
                {% for lab_service in services %}
                    <div class="list-group-item mb-3 mt-2 lab-service-item">
                        <h4 class="mb-1 service-title" data-service-id="{{ lab_service.id }}">
                            {{ lab_service.original_name }}
                        </h4>
                        <div class="lab-service-info">
                            <p><strong>Ціна:</strong> {{ lab_service.price }} грн</p>
                            <p><strong>Час виконання:</strong> {{ lab_service.execution_time }}</p>
                            <p><strong>Лабораторія:</strong> {{ lab_service.lab.lab_name }}</p>
                        </div>
                        <a href="{{ lab_service.url }}" class="btn btn-sm btn-primary button-hover" target="_blank">Перейти</a>
                    </div>
                {% endfor %}
            </div>
        </div>
        </div>
        {% endif %}
    </div>
</div>


{% block footer %}

{% include "footer.html" %}
{% endblock %}
{% endblock %}